
services:
  - type: web
    name: portfolio-backend
    env: node
    region: oregon
    plan: starter
    repo: https://github.com/yourusername/yourrepo.git
    branch: main
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGO_URI
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false

static_sites:
  - type: static
    name: portfolio-frontend
    repo: https://github.com/yourusername/yourrepo.git
    branch: main
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_BASE
        sync: false
